trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      python --version
      pip --version
    displayName: "Check Python and Pip Versions"

  - script: |
      docker --version
    displayName: "Check Docker Version"

  - script: |
      docker build -t myapp:latest .
      docker run -d -p 5000:5000 myapp:latest
    displayName: "Build and Run Docker Container"
